site_name: OpenUnderstand Docs (v0.1.1dev)
site_url: https://m-zakeri.github.io/OpenUnderstand
repo_url: https://github.com/m-zakeri/OpenUnderstand
site_description: An open-source implementation of Understand Python API for Java language
site_author: Morteza Zakeri
copyright: © 2021-2022 OpenUnderstand project - IUST Reverse Engineering Research Laboratory

theme:
  name: material
  palette:
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - import os
          selection:
            members: True

nav:
    - Home: index.md
    - API reference: api.md
    - Kinds: kinds.md
    - Architecture: architecture.md
    - Parity with Understand: parity.md
    - Issue tracker: 'https://github.com/m-zakeri/OpenUnderstand/issues'
