# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import pynguin_target as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    class_type_data_adapter_0 = module_0.ClassTypeDataAdapter()
    assert class_type_data_adapter_0.package_name == ""
    assert class_type_data_adapter_0.file_path == ""
    class_type_data_adapter_0.get_long_name()


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    class_type_data_adapter_0 = module_0.ClassTypeDataAdapter()
    assert class_type_data_adapter_0.package_name == ""
    assert class_type_data_adapter_0.file_path == ""
    class_type_data_adapter_0.set_parent_class(none_type_0)
    class_type_data_adapter_1 = module_0.ClassTypeDataAdapter()
    assert class_type_data_adapter_1.package_name == ""
    assert class_type_data_adapter_1.file_path == ""
    class_type_data_adapter_1.get_long_name()


def test_case_2():
    class_type_data_adapter_0 = module_0.ClassTypeDataAdapter()
    assert class_type_data_adapter_0.package_name == ""
    assert class_type_data_adapter_0.file_path == ""
    class_type_data_adapter_0.has_parent()


def test_case_3():
    int_0 = -573
    class_type_data_adapter_0 = module_0.ClassTypeDataAdapter()
    assert class_type_data_adapter_0.package_name == ""
    assert class_type_data_adapter_0.file_path == ""
    class_type_data_adapter_0.set_package_name(int_0)
    class_type_data_adapter_1 = module_0.ClassTypeDataAdapter()
    assert class_type_data_adapter_1.package_name == ""
    assert class_type_data_adapter_1.file_path == ""
    class_type_data_adapter_1.has_parent()


@pytest.mark.xfail(strict=True)
def test_case_4():
    class_type_data_adapter_0 = module_0.ClassTypeDataAdapter()
    assert class_type_data_adapter_0.package_name == ""
    assert class_type_data_adapter_0.file_path == ""
    class_type_data_adapter_1 = module_0.ClassTypeDataAdapter()
    assert class_type_data_adapter_1.package_name == ""
    assert class_type_data_adapter_1.file_path == ""
    class_type_data_adapter_1.set_child_class(class_type_data_adapter_0)
    class_type_data_adapter_1.get_long_name()
