com::calculator::app::method::basic_operation
static double multiplication(double a, double b)
static int multiplication(int a, int b)
Referenced by integral.calculate_pow_x_n, integral.calculate_x.
static double pow(double a, double power)
Referenced by integral.calculate_pow_x_n.
static double sum(double a, double b)
static int sum(int a, int b)
Referenced by fibonacci.calculate_to_n.